name: build-virtual-env
description: Build a virtual environment
runs:
  using: composite
  steps:
    - name: build-virtual-env
      run: |
        echo -e "\033[1;32m**** BUILDING VIRTUAL ENVIRONMENT ****\033[0m"
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
