[tool.ruff]
target-version = "py312"
line-length = 88
indent-width = 4

[tool.ruff.lint]

select = [
    "ERA",
    "YTT",
    "ANN",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "EM",
    "FIX",
    "INT",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SIM",
    "TID",
    "TD",
    "TC",
    "ARG",
    "PTH",
    "FLY",
    "I",
    "C90",
    "N",
    "PERF",
    "E",
    "W",
    "D",
    "F",
    "PL",
    "FURB",
    "RUF",
    "TRY"
]
ignore = [
    "D202",
    "D203",
    "D205",
    "D206",
    "D213",
    "D200",
    "D300",
    "D413",
    "D212",
    "W191",
    "E111",
    "E114",
    "E117",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
]

[tool.ruff.lint.per-file-ignores]
"code_quality/tests/**/test_*" = [
    "D400",
    "ANN001",
    "ANN201",
    "S101",
    "S311"
]
"code_quality/tests/**/conftest.py" = [
    "ANN001",
    "S311"
]
"code_quality/tests/**/tools.py" = [
    "S311"
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
docstring-code-format = true

[tool.coverage.report]
exclude_also = [
    'if __name__ == .__main__.:',
]
