name: python-build-virtual-environment

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build-virtual-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set-up-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: build-virtual-env
        run: |
          echo -e "\033[1;32m**** BUILDING VIRTUAL ENVIRONMENT ****\033[0m"
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
